# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('day_request_count', models.IntegerField(default=0)),
                ('minute_request_count', models.IntegerField(default=0)),
                ('latest_request', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('metering_rate', models.IntegerField()),
                ('throttling_rate', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DDAPIwebsite.UserGroup'),
        ),
    ]
