# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDAPIwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latest_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
